### ISSUE TITLE
`Jsoup` Direct vulnerabilities: `CVE-2022-36033`. Vulnerabilities from dependencies: `CVE-2023-26049`, `CVE-2023-26048`

### ISSUE THREAD

**Issue by geugenm** [geugenm/student-bsu-by#5]
### Solution: update `jsoup` package to `1.16.1`

**But some Kotlin code updates required**

### Error log:
```
student-bsu-by/app/src/main/java/github/alexzhirkevich/studentbsuby/repo/HostelRepository.kt:77:75 Expected 2 parameters of types Node!, Int
student-bsu-by/app/src/main/java/github/alexzhirkevich/studentbsuby/repo/HostelRepository.kt:77:75 Type mismatch: inferred type is () -> NodeFilter.FilterResult! but ((Node!, Int) -> NodeFilter.FilterResult!)! was expected
student-bsu-by/app/src/main/java/github/alexzhirkevich/studentbsuby/repo/HostelRepository.kt:77:77 Unresolved reference: it
student-bsu-by/app/src/main/java/github/alexzhirkevich/studentbsuby/repo/HostelRepository.kt:81:73 Expected 2 parameters of types Node!, Int
student-bsu-by/app/src/main/java/github/alexzhirkevich/studentbsuby/repo/HostelRepository.kt:81:73 Type mismatch: inferred type is () -> NodeFilter.FilterResult! but ((Node!, Int) -> NodeFilter.FilterResult!)! was expected
student-bsu-by/app/src/main/java/github/alexzhirkevich/studentbsuby/repo/HostelRepository.kt:81:76 Unresolved reference: it
```

**Comment by geugenm** [comment]
NOTE: error log is compilation error after upgrade to 1.15+ versions of jsoup(which are also vulnerable)

**Comment by geugenm** [comment]
Created a pull request with the fixed issue. Needs some tests
